import React, {useState, useEffect, ReactNode} from 'react';
import Head from 'next/head'
import fetch  from 'isomorphic-unfetch';
import styles from '../styles/Home.module.css'
import Layout from '@components/Layout/Layout';
import Card from '@components/Card/Card';

export const getServerSideProps = async () => {
  const response = await fetch('https://pokeapi.co/api/v2/pokemon?offset=0&limit=50')
  const {results} = await response.json() 
  

  const resultados = await Promise.all(
    results.map(async (poke:any) => {
      let pokeDetail = await fetch(poke.url)
      return pokeDetail.json()
    })
  )
  
  return {
    props:{
      pokemonList : resultados,
    }
  }
}

function Home({pokemonList}) {

  const [pokemons,setPokemons] = useState(pokemonList)
  const filter = (data: string) => {
    const arrayFilter = pokemonList.filter((pokemon: any) =>{
      
      if(pokemon.name.indexOf(data) !== -1 || pokemon.id == data) {
        return pokemon
      }
    })
    setPokemons(arrayFilter)
  }

  return (
    <Layout filter={filter}>
      <div className={styles.grid}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section className={styles.grid}>
          {pokemons.length == 0 
            ?<div>No se encontraron pokemones</div>
            :pokemons.map((item: Object)=>{
              return (
                <Card objPokemon={item} />
              );
            })
          } 
        </section>
      </div>
    </Layout>
  );
};

export default Home;
